version: '3.7'

services:
  server:
    image: node:alpine
    container_name: ciciara_server
    expose: [2370]
    ports: 
      - 2370:2370
    working_dir: /home/node/app
    volumes: 
      - ./server:/home/node/app
    command: "npm run watch-node"
    depends_on: 
      - mongo

  mongo:
    image: mongo:bionic
    container_name: ciciara_db
    restart: always
    expose: [27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ciciara
      MONGO_INITDB_ROOT_PASSWORD: ciciara
      MONGO_INITDB_DATABASE: ciciara

  mongo-express:
    image: mongo-express
    container_name: ciciara_db_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ciciara
      ME_CONFIG_MONGODB_ADMINPASSWORD: ciciara

networks: 
    default:
        name: ciciara_default
        driver: bridge
