export const SET_CICIARA_ONLINE = "SET_CICIARA_ONLINE";
export const SET_CICIARA_OFFLINE = "SET_CICIARA_OFFLINE";
export const LOGIN = "LOGIN";
export const APPEND_MESSAGE = "APPEND_MESSAGE";
export const SET_ROOM = "SET_ROOM";
export const UPDATE_USER = "UPDATE_USER";
